Repository d-u-d-e/c-compiler, pull requests merged in 2024-11, with the labels that each got.

#2 Implement compiler driver
  README.md
  compiler_driver.py
  poetry.lock
  pyproject.toml
Labels: enhancement, chapter 1

#6 Implement basic lexer
  compiler/__init__.py
  compiler/compiler_driver.py
  compiler/lexer.py
  pyproject.toml
  tests/lexer/test_lexer.py
  tests/lexer/test_samples/chapter01/multi_digit.c
  tests/lexer/test_samples/chapter01/newlines.c
  tests/lexer/test_samples/chapter01/no_newlines.c
  tests/lexer/test_samples/chapter01/return_0.c
  tests/lexer/test_samples/chapter01/return_2.c
  tests/lexer/test_samples/chapter01/spaces.c
  tests/lexer/test_samples/chapter01/tabs.c
Labels: enhancement, chapter 1

#24 feat(CI): changelog file generation on commit
  .github/workflows/ci-commit-changelog.yaml
Labels: documentation

#22 Implement pre-commit along with Mypy and Ruff
  .pre-commit-config.yaml
  README.md
  compiler/compiler_driver.py
  compiler/lexer.py
  poetry.lock
  pyproject.toml
  tests/test_lexer.py
  tests/test_samples/chapter01/multi_digit.c
  tests/test_samples/chapter01/newlines.c
  tests/test_samples/chapter01/no_newlines.c
  tests/test_samples/chapter01/return_0.c
  tests/test_samples/chapter01/return_2.c
  tests/test_samples/chapter01/spaces.c
  tests/test_samples/chapter01/tabs.c
Labels: good first issue, chore

#25 feat(ci): dependencies caching
  .github/workflows/ci-unittest.yaml
Labels: chore
