Repository d-u-d-e/c-compiler, pull requests merged in 2024-12, with the labels that each got.

#27 Introducing assembly generation
  compiler/assembly_generation/ast.py
  compiler/assembly_generation/generator.py
  compiler/compiler_driver.py
  compiler/parser/ast.py
  compiler/parser/parsers.py
  lib/ast/__init__.py
  lib/ast/ast.py
  lib/tree/tree.py
  tests/test_parsers.py
Labels: enhancement, chapter 1

#28 Assembly code emission
  compiler/assembly_generation/assembly_ast.py
  compiler/assembly_generation/assembly_generation.py
  compiler/code_emission/code_emission.py
  compiler/compiler_driver.py
  compiler/parser/parser.py
  compiler/parser/parser_ast.py
  tests/test_ast.py
  tests/test_parser.py
  tests/test_parsers.py
Labels: enhancement, chapter 1

#31 Release/1.1.0
  .github/workflows/ci-commit-changelog.yaml
  .github/workflows/ci-unittest.yaml
  .gitignore
  .pre-commit-config.yaml
  README.md
  compiler/__init__.py
  compiler/assembly_generation/__init__.py
  compiler/assembly_generation/assembly_ast.py
  compiler/assembly_generation/assembly_generation.py
  compiler/code_emission/__init__.py
  compiler/code_emission/code_emission.py
  compiler/compiler_driver.py
  compiler/lexer/__init__.py
  compiler/lexer/lexer.py
  compiler/parser/__init__.py
  compiler/parser/parser.py
  compiler/parser/parser_ast.py
  lib/__init__.py
  lib/ast/__init__.py
  lib/ast/ast.py
  lib/tree/__init__.py
  lib/tree/node.py
  lib/tree/tree.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/test_ast.py
  tests/test_lexer.py
  tests/test_parser.py
  tests/test_samples/chapter_1/invalid_lex/at_sign.c
  tests/test_samples/chapter_1/invalid_lex/backslash.c
  tests/test_samples/chapter_1/invalid_lex/backtick.c
  tests/test_samples/chapter_1/invalid_lex/invalid_identifier.c
  tests/test_samples/chapter_1/invalid_lex/invalid_identifier_2.c
  tests/test_samples/chapter_1/invalid_parse/end_before_expr.c
  tests/test_samples/chapter_1/invalid_parse/extra_junk.c
  tests/test_samples/chapter_1/invalid_parse/invalid_function_name.c
  tests/test_samples/chapter_1/invalid_parse/keyword_wrong_case.c
  tests/test_samples/chapter_1/invalid_parse/missing_type.c
  tests/test_samples/chapter_1/invalid_parse/misspelled_keyword.c
  tests/test_samples/chapter_1/invalid_parse/no_semicolon.c
  tests/test_samples/chapter_1/invalid_parse/not_expression.c
  tests/test_samples/chapter_1/invalid_parse/space_in_keyword.c
  tests/test_samples/chapter_1/invalid_parse/switched_parens.c
  tests/test_samples/chapter_1/invalid_parse/unclosed_brace.c
  tests/test_samples/chapter_1/invalid_parse/unclosed_paren.c
  tests/test_samples/chapter_1/valid/multi_digit.c
  tests/test_samples/chapter_1/valid/newlines.c
  tests/test_samples/chapter_1/valid/no_newlines.c
  tests/test_samples/chapter_1/valid/return_0.c
  tests/test_samples/chapter_1/valid/return_2.c
  tests/test_samples/chapter_1/valid/spaces.c
  tests/test_samples/chapter_1/valid/tabs.c
  tests/test_tree.py
Labels: chapter 1, release

#53 chore(main): release 0.1.0
  CHANGELOG.md
  pyproject.toml
Labels: autorelease: pending

#72 Lexer: recognize complement and negate operators
  compiler/lexer/lexer.py
  tests/test_lexer.py
  tests/test_samples/chapter_2/invalid_parse/decrement_num.c
  tests/test_samples/chapter_2/valid/nested_ops_2.c
  tests/test_samples/chapter_2/valid/redundant_parens.c
Labels: chapter 2
